name: Run Unit Test and Upload Coverage Report

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened]
  workflow_dispatch:

jobs:
  build-run-upload:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install build packages
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo apt install -y doxygen lcov gcovr
          
      - name: Configure CMake flags and build executables
        run: |
          cmake -D WANT_COVERAGE=ON -D CMAKE_BUILD_TYPE=Debug -S ./ -B build/
          cmake --build build/ --clean-first --target all coverage

      # Check if coverage report is generated
      - name: Check Coverage Report
        run: |
          if [ -f build/coverage.info ]; then
            echo "Coverage report exists:"
            cat build/coverage.info
          else
            echo "Coverage report does not exist."
            exit 1
          fi
      
      - name: Upload coverage result to CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ${{ github.workspace }}/build/coverage.info
          fail_ci_if_error: false # Upload even if tests fail
          verbose: true